#!/bin/sh

set -e

gem install bundler
bundle

if [[ ! -e config/database.yml ]]; then
  cp config/database.yml{.example,}
  createuser truxi --superuser
fi

# Not a complete set of required packages, but some of them
if which apt-get 2>&1 > /dev/null; then
  sudo apt-get install libpq-dev libmagickwand-dev sqlite3 libsqlite3-dev
  gem install pg --version 0.11 -- --with-pg-lib=/usr/lib
fi

rake db:setup
rake
